version: '3'

services:
  postgres:
    image: postgres:10
    build:
      context: ./
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - .:/var/lib/postgresql/10/data
    environment:
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U userdb -d shop" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: ./
    container_name: shop-application
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shop
      - SPRING_DATASOURCE_USERNAME=userdb
      - SPRING_DATASOURCE_PASSWORD=pass